### ISSUE TITLE
Instruction:  how to retrained on different dataset

### ISSUE THREAD

**Issue by luke4u** [Nagakiran1/Extending-Google-BERT-as-Question-and-Answering-model-and-Chatbot#3]
Hi Naga,

Hope you are doing well. 
Is it possible you can share an instruction on how to retrain your model on different dataset? I am  very interested to test your model on new dataset? 

Thanks in advance.
Luke

**Comment by Nagakiran1** [comment]
Hi Luke,
Thanks for your response.
According to the followed approach, model does'nt need any retraining.
We are utilizing the trained BERT Question and answering feature to apply directly on our specific data. To apply that specific format of data (DocumentData.txt) preparation followed (https://github.com/Nagakiran1/Extending-Google-BERT-as-Question-and-Answering-model-and-Chatbot#data-preparation).

It could give satisfactory results, if the questions and summary similar to the SQuAD dataset format.
If its not giving expected results, there might be need of retraining the BERT model on specific data :-|.

Thanks,
Naga.

**Comment by vinnytwice** [comment]
Hi, I'm not sure I understand How to prepare custom dataset to fine-tune Bert.
when you say " The data wants to for the Questioning the BERT has to be copied in simple text file, delimiting with three '\n'. " What does it mean " delimiting with three '\n' " ?
As I see your data.txt file has 2 empty lines between paragraphs. Is it all you need to properly separate them?
Thank you for your repo and great articles, I'm very new to all this and you are the one who explained it very clearly, dough my luck of expertise in the field is not making me understand a couple of details. 
Thanks again.
Vincenzo

**Comment by vinnytwice** [comment]
Hi guys,
I'm not sure I understand How to prepare custom dataset to fine-tune Bert.
In the linked instructions i read " The data wants to for the Questioning the BERT has to be copied in simple text file, delimiting with three '\n'. " What does it mean " delimiting with three '\n' " ?
As I see the data.txt file simply has 2 empty lines between paragraphs. Is it all that is needed to properly separate them?
Thank you for your explanations  
Vincenzo

**Comment by luke4u** [comment]
Thanks Naga for answering. It's really helpful!
